### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by snehitvaddi** [Biswa5812/EzAccess#1]
Hey Biswa!!
Good to see this application. If possible just add `How to run` and `Output` in Readme file. So that it would be easy to run even for a beginner.

**Comment by Biswa5812** [comment]
@snehitvaddi Thank you very much for your suggestion, we will be updating that by tomorrow for sure!!

**Comment by NavaneethNidadavolu** [comment]
Hey @Biswa5812, On that note add "requirements.txt" file so that the prerequisite packages can be installed easily.

**Comment by Biswa5812** [comment]
Hello @NavaneethNivol, thank you for pointing that feature out.
I have added the requirements.txt folder!!
